name: Process Community Contributions

on:
  workflow_dispatch:  # Permet de déclencher manuellement
  repository_dispatch:
    types: [new-contribution]  # Déclenché par l'API serverless
  schedule:
    - cron: '0 */6 * * *'  # Exécution toutes les 6 heures

jobs:
  process-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Nécessaire pour push les modifications

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies with retry
        run: |
          for i in {1..3}; do
            echo "Tentative $i d'installation des dépendances..."
            if npm ci; then
              echo "Installation réussie"
              break
            else
              echo "Échec de la tentative $i"
              if [ $i -eq 3 ]; then
                echo "Toutes les tentatives ont échoué"
                exit 1
              fi
              echo "Attente de 30 secondes avant nouvelle tentative..."
              sleep 30
            fi
          done

      - name: Install additional dependencies for processing
        run: |
          npm install node-fetch@2 sharp uuid

      - name: Process pending contributions
        run: node .github/scripts/process-contribution.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add entries.json images/ thumbnails/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update community content [skip ci]"
          git push
