name: Synchronize Issues to entries.json

on:
  issues:
    types: [opened, closed, edited, labeled]  # Déclenchement immédiat
  workflow_dispatch:  # Manuel
  schedule:
    - cron: '*/2 * * * *'  # Vérifier toutes les 2 minutes (au lieu de 5)

# Éviter les exécutions concurrentes sur la même branche
concurrency:
  group: sync-entries-${{ github.ref }}
  cancel-in-progress: true  # Annuler les anciens runs pour éviter l'accumulation

jobs:
  sync-entries:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Nécessaire pour pousser des modifications
      issues: read     # Nécessaire pour lire les issues

    steps:
      - name: Wait for other workflows
        run: sleep 10  # Attendre 10 secondes pour regrouper les modifications

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupérer tout l'historique

      - name: Pull latest changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Process contributions from issues
        run: |
          # Script unifié qui remplace tous les autres
          node .github/scripts/unified-contribution-processor.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add entries.json images/ thumbnails/
          if ! git diff --staged --quiet; then
            git commit -m "Update entries.json from GitHub issues [skip ci]"
            git push origin main
            
            # Déclencher IMMÉDIATEMENT la synchronisation dans l'app principale
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/CollectifFeydeau/1Hall1Artiste/dispatches \
              -d '{"event_type":"community-content-updated"}' &
            
            echo "✅ Synchronisation déclenchée dans l'app principale"
          else
            echo "No changes to commit"
          fi
